### ISSUE TITLE
http 1.0

### ISSUE THREAD

**Issue by yanqingdegithub-yan** [wslaimin/http_proxy#6]
有考虑把http支持到1.0版本以上吗

**Comment by lzou** [comment]
啥时候支持下http 1.0.0呢？

**Comment by CloudIQTechnologies** [comment]
Have you considered supporting http to version 1.0 or above?  When will http 1.0.0 be supported?

**Comment by CloudIQTechnologies** [comment]
We already have have a PR (https://github.com/wslaimin/http_proxy/pull/7) for supporting http version 1.0
This PR was created by @pbaradziej and I have reviewed it
@wslaimin can you please merge this PR?

**Comment by wslaimin** [comment]
1.2.2移除了http依赖，使用依旧
